{
  "formatVersion": "1.1",
  "component": {
    "group": "com.indigobyte",
    "module": "jsonld-metadata",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jsonld-metadata-1.0.1.jar",
          "url": "jsonld-metadata-1.0.1.jar",
          "size": 7385741,
          "sha512": "236188435b824907815268eed28a5356ca37ad955c6665269e043d8bdf4a84296decd522e2d5461d9dc000bf9c3feaac29faf5b1120cb0c0cce8c6e63932fda8",
          "sha256": "f85312b69321fe2bf9d3dd293d063cf6443c6b5c023e1d8fd69c6f9d2194f0b6",
          "sha1": "ff7a65ee912f71c744e42a90a5dd593dd2283794",
          "md5": "47897f30da04572efa296e0979901aff"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.5.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "21.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "jsonld-metadata-1.0.1.jar",
          "url": "jsonld-metadata-1.0.1.jar",
          "size": 7385741,
          "sha512": "236188435b824907815268eed28a5356ca37ad955c6665269e043d8bdf4a84296decd522e2d5461d9dc000bf9c3feaac29faf5b1120cb0c0cce8c6e63932fda8",
          "sha256": "f85312b69321fe2bf9d3dd293d063cf6443c6b5c023e1d8fd69c6f9d2194f0b6",
          "sha1": "ff7a65ee912f71c744e42a90a5dd593dd2283794",
          "md5": "47897f30da04572efa296e0979901aff"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jsonld-metadata-1.0.1-javadoc.jar",
          "url": "jsonld-metadata-1.0.1-javadoc.jar",
          "size": 20729116,
          "sha512": "25a470d215d8f3f9b537c4c0b1081170733b1405fac001d38d50bbd607f9ef18b8d62d48f8de9e35c9986990827c4644640045fff3f9a0dffe280ea8d1d04171",
          "sha256": "8cdcc3ab3b60474f46b6559931b17be6b1a80a424d8902d4ae9ff64eda6b549c",
          "sha1": "e09c6c13f9be4219970761707a41dcca217fcca2",
          "md5": "d15159aaee38f1878b091ba7cb4e4fb0"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jsonld-metadata-1.0.1-sources.jar",
          "url": "jsonld-metadata-1.0.1-sources.jar",
          "size": 5907839,
          "sha512": "ebd94214fe435df50eff1f2e4e78682e09d457cf03b98ad58da163bed78a8fc4a97c528d32f9034abf6e1aa636fdc031a8b8d1a8c7026e63813d49763e9e5a6a",
          "sha256": "7c284493a8e4997160a1c6bfcff9bd72a070260208897d710248440b32daef72",
          "sha1": "53e755603bcae7a4de2dcbd3ac6b7f09bfd57fdb",
          "md5": "03046fd6a1b30340142399b71b27bd88"
        }
      ]
    }
  ]
}
