{
  "formatVersion": "1.1",
  "component": {
    "group": "com.indigobyte",
    "module": "jsonld-metadata",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jsonld-metadata-1.0.1.jar",
          "url": "jsonld-metadata-1.0.1.jar",
          "size": 7061687,
          "sha512": "30c0ca7e3c8ff7851b124da0a9fae729e203451982b00e765fe07872a8991597fcab774ff70990b9ffe6e8ecd4216466a098b3a6a309cd97514b5a37b2e748e9",
          "sha256": "0a4dff92f923c0cd4e0b571feacc6046fec624132855bc8b92c0fce61ad09f80",
          "sha1": "44d1892cfa305d0e411cb2268a181b0fcfd74335",
          "md5": "63744fcc86e3b406fe85757e401a1e75"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.5.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "21.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "jsonld-metadata-1.0.1.jar",
          "url": "jsonld-metadata-1.0.1.jar",
          "size": 7061687,
          "sha512": "30c0ca7e3c8ff7851b124da0a9fae729e203451982b00e765fe07872a8991597fcab774ff70990b9ffe6e8ecd4216466a098b3a6a309cd97514b5a37b2e748e9",
          "sha256": "0a4dff92f923c0cd4e0b571feacc6046fec624132855bc8b92c0fce61ad09f80",
          "sha1": "44d1892cfa305d0e411cb2268a181b0fcfd74335",
          "md5": "63744fcc86e3b406fe85757e401a1e75"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jsonld-metadata-1.0.1-javadoc.jar",
          "url": "jsonld-metadata-1.0.1-javadoc.jar",
          "size": 19625377,
          "sha512": "8c8fbe9e80b303d541ef3036f3a9b0a35c0083e81d0764000b15d98e6703a33ed2c030fde7690f0332f1885bc7ad32e7799c70141c1cc9bb23a5c8a54bfd64bd",
          "sha256": "a2021657e58a9d8a03184f37d651943a3c29b62582e3a645d18e5248329eac35",
          "sha1": "466e9d3cc3e6a265dc3b9931f9b12de4bd6bf339",
          "md5": "5ad52c5b5a30a688abf2edc1d54448b3"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jsonld-metadata-1.0.1-sources.jar",
          "url": "jsonld-metadata-1.0.1-sources.jar",
          "size": 5505448,
          "sha512": "d460bd2f84d74259a509517fd53a0faabbc5dd9a8bcab3751f1d864dd015c1088f004acb48fc94270ea460ec85a144e13db2075cd431b1b07330e3e534cf420e",
          "sha256": "07a686874b9b2c3d3113186fa39c7a29fbeb415d9af77fdd44f389dc6b3d1c0d",
          "sha1": "fa70562d5f90d38e4499c3246b17b761dab9711b",
          "md5": "ab9c1e8070962fd661f30b82e1268188"
        }
      ]
    }
  ]
}
