{
  "formatVersion": "1.1",
  "component": {
    "group": "com.indigobyte",
    "module": "jsonld-metadata",
    "version": "1.0.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.1.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jsonld-metadata-1.0.1.jar",
          "url": "jsonld-metadata-1.0.1.jar",
          "size": 10339214,
          "sha512": "943975caa67b47e46c36d509b7336d65d411cf22dd462e7e7a1a1a1fde69442bebc65db68dc08c5ef2f0eb3e9dd67498d5986eac8db989d29f99f815a44a8af1",
          "sha256": "aed23455a76888c71b94727ee62d6c2b63300be9a43688f9f13630aabcab5d49",
          "sha1": "0cedcefa6e880abf14e2be77c7d97ce8eceea30c",
          "md5": "dced38501466dd0cb9415e3373bebabd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 16,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.fasterxml.jackson.core",
          "module": "jackson-databind",
          "version": {
            "requires": "2.10.5.1"
          }
        },
        {
          "group": "org.jetbrains",
          "module": "annotations",
          "version": {
            "requires": "21.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "jsonld-metadata-1.0.1.jar",
          "url": "jsonld-metadata-1.0.1.jar",
          "size": 10339214,
          "sha512": "943975caa67b47e46c36d509b7336d65d411cf22dd462e7e7a1a1a1fde69442bebc65db68dc08c5ef2f0eb3e9dd67498d5986eac8db989d29f99f815a44a8af1",
          "sha256": "aed23455a76888c71b94727ee62d6c2b63300be9a43688f9f13630aabcab5d49",
          "sha1": "0cedcefa6e880abf14e2be77c7d97ce8eceea30c",
          "md5": "dced38501466dd0cb9415e3373bebabd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jsonld-metadata-1.0.1-javadoc.jar",
          "url": "jsonld-metadata-1.0.1-javadoc.jar",
          "size": 29159480,
          "sha512": "a309a99d085a5c74fe31aad58b3c84a7031bb04f5704050fa7f0cabf4785d8636f401aa2ac985145b4f7e41012cc91e6ea5a4460f2e47fef6d68d7006bc3eee9",
          "sha256": "a03915f15fa50d410ab0561134e092a837b838d3af5965fb2260d1688a19f6c8",
          "sha1": "84c5fccaad653ee2b4dd6fa9f765b619c45a97fc",
          "md5": "89e90c0977d7fed8892058cd3a435ef1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jsonld-metadata-1.0.1-sources.jar",
          "url": "jsonld-metadata-1.0.1-sources.jar",
          "size": 8127062,
          "sha512": "f1728dc1e1f82dbc468e5c625f60f0913bfd4a51c89b7a0db9ec14fb30b85d0e99270597f0cecd18791631a673324b47076debcfffe03a1740bd5a819ebdc93b",
          "sha256": "87017aa8183fa11517a99d7ebe9a357422b207a40966da4fc32006f3c8acb8a8",
          "sha1": "86cf0c035adcbec6163b62ffec64488e88ff93e9",
          "md5": "f140cfcf93c5ac719a25958ec4e8647e"
        }
      ]
    }
  ]
}
